
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjkxMzQyOTk2","is_bot":false,"login":"MeDotE","name":"Mike Jiang"},"headRefName":"mike-HomeController","number":23,"title":"mj - finished home controller and tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-3/pull/23"},{"author":{"id":"MDQ6VXNlcjkxMzQyOTk2","is_bot":false,"login":"MeDotE","name":"Mike Jiang"},"headRefName":"mike-jokecontroller","number":22,"title":"mj - finished controller for joke","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-3/pull/22"},{"author":{"id":"MDQ6VXNlcjQyOTg1Njg3","is_bot":false,"login":"ericpretzel","name":"Eric W"},"headRefName":"Eric-LocationQueryController","number":21,"title":"Add location query controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-3/pull/21"}]
