
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzMzMzNDUz","is_bot":false,"login":"a-k-u-m-a-r","name":"Akshay Kumar"},"headRefName":"Akshay-University-Controller","number":36,"title":"Add University Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-3/pull/36"},{"author":{"id":"MDQ6VXNlcjM4NzAyMjEx","is_bot":false,"login":"tim-choi","name":"Timothy Choi"},"headRefName":"TC-Zipcode-Controller","number":35,"title":"Add ZipCode Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-3/pull/35"}]
