
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjM4NzAyMjEx","is_bot":false,"login":"tim-choi","name":"Timothy Choi"},"headRefName":"TCZipSvc","number":33,"title":"Add ZipCode Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-3/pull/33"},{"author":{"id":"MDQ6VXNlcjUxODg2NTU1","is_bot":false,"login":"coder626","name":""},"headRefName":"Kevin-PublicHolidayController","number":32,"title":"Controller and Tests Pass","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-3/pull/32"}]
